---
title: Code herhalen met for-lussen in Python
hero_image: images/banner.png
description: generieke-python-for-loop-repeat beschrijving
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-08-24"
steps:
  - 
    title: Code herhalen met for-lussen in Python
