title: Repeating code with for loops in Python
hero_image: images/banner.png
description: generic-python-for-loop-repeat description
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-08-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
