---
title: Repetindo o código com ciclos for em Python
hero_image: images/banner.png
description: como repetir códigos com ciclos for em Python
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-08-24"
steps:
  - 
    title: Repetindo o código com ciclos for em Python
