---
title: تكرار تعليمات برمجية مع حلقات for في Python
hero_image: images/banner.png
description: وصف عام للحلقات التكرارية في Python
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-08-24"
steps:
  - 
    title: تكرار تعليمات برمجية مع حلقات for في Python
