---
title: Répétition de code avec des boucles for en Python
hero_image: images/banner.png
description: description générique-python-boucle-for--répétition
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-08-24"
steps:
  - 
    title: Répétition de code avec des boucles for en Python
